/*
 *  DefineHotelResq.h
 *  ElongClient
 *
 *  Created by bin xing on 11-3-6.
 *  Copyright 2011 DP. All rights reserved.
 *
 */
#import "DefineCommon.h"

#define ReqHO_HotelOrderNo_I					@"OrderNo"
#define ReqHO_Currency							@"Currency"
#define ReqHO_HotelId_S							@"HotelId"
#define ReqHO_RoomTypeId_S						@"RoomTypeId"
#define ReqHO_RatePlanID_L						@"RatePlanID"
#define ReqHO_ArriveDate_ED						@"ArriveDate"
#define ReqHO_LeaveDate_ED						@"LeaveDate"
#define ReqHO_ArriveTimeEarly_ED				@"ArriveTimeEarly"
#define ReqHO_ArriveTimeLate_ED					@"ArriveTimeLate"
#define ReqHO_TotalPrice_D						@"TotalPrice"
#define ReqHO_RoomCount_I						@"RoomCount"
#define ReqHO_GuestNames_A						@"GuestNames"
#define ReqHO_GuestType							@"GuestType"
#define ReqHO_ExtendByteField					@"ExtendByteField"
#define ReqHO_ExtendDespField					@"ExtendDespField"
#define ReqHO_ConnectorMobile_S					@"ConnectorMobile"
#define ReqHO_ConnectorName_S					@"ConnectorName"
#define ReqHO_SelectedCoupons_A					@"SelectedCoupons"
#define ReqHO_HotelCoupon_DI					@"HotelCoupon"
#define ReqHO_NotesToElong_S					@"NotesToElong"
#define ReqHO_NotesToHotel_S					@"NotesToHotel"
#define ReqHO_VouchMoney_D						@"VouchMoney"
#define ReqHO_VouchSetType_I					@"VouchSetType"
#define ReqHO_IsNeedInvoice                     @"IsNeedInvoice"
#define ReqHO_CreditCard_DI						@"CreditCard"
#define ReqHO_CustomerInvoice                   @"CustomerInvoice"
#define ReqHO__ElongCardNo_L						@"ElongCardNo"
#define ReqHO__CreditCardType_DI					@"CreditCardType"
#define ReqHO___ID_S									@"Id"
#define ReqHO___Name_S									@"Name"
#define ReqHO__CreditCardNumber_S					@"CreditCardNumber"
#define ReqHO__HolderName_S							@"HolderName"
#define ReqHO__VerifyCode_S							@"VerifyCode"
#define ReqHO__CertificateType_I					@"CertificateType"
#define ReqHO__CertificateNumber_S					@"CertificateNumber"
#define ReqHO__ExpireYear_I							@"ExpireYear"
#define ReqHO__ExpireMonth_I						@"ExpireMonth"
/*****************************************************************************************/
#define ReqHS_CityName_S			@"CityName"
#define ReqHS_AreaName_S			@"AreaName"
#define ReqHS_HotelName_S			@"HotelName"
#define ReqHS_IntelligentSearchText @"IntelligentSearchText"
#define ReqHS_HotelBrandID			@"HotelBrandID"
#define ReqHS_MutilpleFilter		@"MutilpleFilter"
#define ReqHS_FacilitiesFilter      @"FacilitiesFilter"
#define ReqHS_ThemesFilter          @"ThemesFilter"
#define ReqHS_NumbersOfRoom         @"NumbersOfRoom"
#define ReqHS_PriceLevel            @"PriceLevel"
#define ReqHS_HighestPrice_I		@"HighestPrice"
#define ReqHS_LowestPrice_I			@"LowestPrice"
#define ReqHS_Radius_D				@"Radius"
#define ReqHS_MemberLevel           @"MemberLevel"
#define ReqHS_CheckInDate_ED		@"CheckInDate"
#define ReqHS_CheckOutDate_ED		@"CheckOutDate"
#define ReqHS_StarCode_I			@"StarCode"
#define ReqHS_OrderBy_I				@"OrderBy"
#define ReqHS_IsPositioning_B		@"IsPositioning"
#define ReqHS_Longitude_B			@"Longitude"
#define ReqHS_Latitude_B			@"Latitude"
#define ReqHS_PageSize_I			@"PageSize"
#define ReqHS_PageIndex_I			@"PageIndex"
#define ReqHS_TonightPageIndex_I    @"TPageIndex"
#define ReqHS_Filter				@"Filter"
#define ReqHS_IsApartment  @"IsApartment"
#define ReqHS_SEARCHGPS				@"IsSearchAgain"
#define ReqHS_VIP                   @"IsVIPSelected"
#define ReqHS_SearchType            @"SearchType"
/*****************************************************************************************/
#define ReqHC_HotelId_S				@"HotelId"
#define ReqHC_PageSize_I			@"PageSize"
#define ReqHC_PageIndex_I			@"PageIndex"
/*****************************************************************************************/
#define ReqHD_HotelId_S				@"HotelId"
#define ReqHD_CheckInDate_ED		@"CheckInDate"
#define ReqHD_CheckOutDate_ED		@"CheckOutDate"
#define ReqHD_CurrencySupport		@"CurrencySupport"
/*****************************************************************************************/
#define ReqHAF_HotelId_S			@"HotelId"
/*****************************************************************************************/
#define ReqHF_PageSize_I			@"PageSize"
#define ReqHF_PageIndex_I			@"PageIndex"
/*****************************************************************************************/